// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MMPSystemManager.DBContext;
using System;

namespace MMPSystemManager.Migrations
{
    [DbContext(typeof(MMPContext))]
    [Migration("20171202110826_1202")]
    partial class _1202
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("MMPSystemManager.Module.AdminInfo", b =>
                {
                    b.Property<string>("AdminNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdminContactEmail");

                    b.Property<string>("AdminContactPhone");

                    b.Property<string>("AdminGrade");

                    b.Property<string>("AdminId");

                    b.Property<string>("AdminIdPict");

                    b.Property<DateTime>("AdminLogTime");

                    b.Property<string>("AdminName");

                    b.Property<string>("AdminPicture");

                    b.Property<string>("Remark");

                    b.HasKey("AdminNumber");

                    b.ToTable("AdminInfos");
                });

            modelBuilder.Entity("MMPSystemManager.Module.AdminLog", b =>
                {
                    b.Property<string>("AdminNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AdminLoginTime");

                    b.Property<bool>("AdminOnline");

                    b.Property<string>("AdminPasswd");

                    b.Property<string>("Remark");

                    b.HasKey("AdminNumber");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("MMPSystemManager.Module.AdminUploadPicture", b =>
                {
                    b.Property<string>("AdminNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdminUploadPict");

                    b.Property<DateTime>("AdminUploadTime");

                    b.Property<string>("Remark");

                    b.HasKey("AdminNumber");

                    b.ToTable("AdminUploadPictures");
                });

            modelBuilder.Entity("MMPSystemManager.Module.Userinfo", b =>
                {
                    b.Property<Guid>("UserNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Remark");

                    b.Property<string>("UserContactEmail");

                    b.Property<string>("UserContactPhone");

                    b.Property<string>("UserFacepict");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.Property<DateTime>("UserPicTime");

                    b.Property<string>("UserWechatName");

                    b.HasKey("UserNumber");

                    b.ToTable("Userinfos");
                });

            modelBuilder.Entity("MMPSystemManager.Module.Userpicture", b =>
                {
                    b.Property<string>("UserNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Remark");

                    b.Property<string>("UserAerialPict");

                    b.Property<string>("UserChoosePict");

                    b.Property<string>("UserName");

                    b.Property<DateTime>("UserPicTime");

                    b.Property<string>("UserPictureLocation");

                    b.HasKey("UserNumber");

                    b.ToTable("Userpictures");
                });
#pragma warning restore 612, 618
        }
    }
}
